import { AfterViewInit, EventEmitter, OnDestroy, OnInit } from '@angular/core';
import { BydBaseComponent } from '@beyond/utils';
import { Observable } from 'rxjs';
import ImageEditor from 'tui-image-editor';
import * as i0 from "@angular/core";
type Selection = 'line' | 'shape' | 'text' | '';
type ShapeSelection = 'rect' | 'triangle' | 'circle' | 'line' | '';
export declare class FilesAnnotationComponent extends BydBaseComponent implements OnInit, AfterViewInit, OnDestroy {
    imagePath: string;
    saveImage$: Observable<null>;
    savedImage: EventEmitter<Blob>;
    tuiImageEditor: ImageEditor;
    selection: Selection;
    shapeSelection: ShapeSelection;
    colorHexa: string;
    colorList: string[];
    objectActivated: null;
    brushSize: number;
    readonly isLight: (color: string) => boolean;
    private _containerRef;
    private _tuiRef;
    private _canvasSize;
    private _intoDrawing;
    constructor();
    ngOnInit(): void;
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    getHeight(): string;
    getWidth(): string;
    keyPress(event: KeyboardEvent): void;
    showPanel(): boolean;
    changeSelection(newSelection: Selection): void;
    changeShapeSelection(newSelection: ShapeSelection): void;
    undo(): void;
    redo(): void;
    shape(type: 'rect' | 'circle' | 'triangle'): void;
    drawing(type: 'LINE_DRAWING' | 'FREE_DRAWING'): void;
    text(): void;
    changeColor(color: string): void;
    changeBrushSize(size: string): void;
    clear(): void;
    validation(): void;
    onSaveClick: () => Promise<void>;
    private _createImageEditor;
    private _stopDrawing;
    private _reflow;
    private _getSettings;
    static ɵfac: i0.ɵɵFactoryDeclaration<FilesAnnotationComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<FilesAnnotationComponent, "byd-files-annotation", never, { "imagePath": { "alias": "imagePath"; "required": false; }; "saveImage$": { "alias": "saveImage$"; "required": false; }; }, { "savedImage": "savedImage"; }, never, never, true, never>;
}
export {};
